### ISSUE TITLE
Error Building the Image

### ISSUE THREAD

**Issue by peel70** [dimtass/meta-nanopi-neo4#1]
Hello,
I'm trying to build an image for a NEO PI4 device but I'm falling in this error following your README.

~/neopi4/build$ bitbake rk-image-base
Parsing recipes: 100% |##############################################################################################################| Time: 0:01:08
Parsing of 2202 .bb files complete (0 cached, 2202 parsed). 3184 targets, 99 skipped, 0 masked, 0 errors.
ERROR: No recipes available for:
  /home/enricopelo/neopi4/sources/meta-nanopi-neo4/recipes-graphics/libdrm/libdrm_rk.bbappend
  /home/enricopelo/neopi4/sources/meta-nanopi-neo4/recipes-graphics/libgles/rockchip-mali_rk.bbappend

maybe something that I forget in local.conf?

Best regards
Enrico

**Comment by dimtass** [comment]
Hi @peel70 ,

I guess you mean nanopi-neo4 SBC right?

Probably the issue you have has to do with the meta-rockchip layer.
You need to clone the layers listed in the README.md file and then also checkout the branches that I've listed for each meta layer, otherwise you may get build errors.

Also have in mind that there's a branch with a newer kernel, which doesn't support OpenGL thoug (just saying if you don't need accelerated graphics).

**Comment by peel70** [comment]
Hi @dimtass,
was my mistake, I've resync with the commit # as reported in your README and I was able to build the image.
Best regards
Enrico

**Comment by dimtass** [comment]
Nice to know that you're able to build now.

Regards,
Dimitris
